
START_TAG = "START"
START_WORD = "<s>"
END_TAG = "END"
END_WORD = "</s>";
AGGREGATION_TAG = "AGR"
ALL_AGGREGATION_TAGS = ["AGR", "AGRCount", "AggFunction"]
GROUP_BY_TAG = "GBC"
SAME_CHUNK_TAG = "I"
TYPE_TAGS = ["FMI", "TMI", "CMI"]
DIVIDER_TAGS = ["FDI", "TEI"]
EVENT_TAGS = ["CE", "FNE", "FDE", "TSE", "TEE", "TBE"]

TIME_TAGS = ["TMI", "TSI", "TSE", "TEI", "TEE", "TBE"]
COUNT_TAGS = ["CMI", "CE"]
FRACTION_TAGS = ["FMI", "FNE", "FDI", "FDE"]


